// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZmL4sM7MAkhNP7eVWZ8r4L2-nDYQUnzw',
    appId: '1:193187845880:web:812f7d3fa8cded78db0d0d',
    messagingSenderId: '193187845880',
    projectId: 'e-commrce-4c2bb',
    authDomain: 'e-commrce-4c2bb.firebaseapp.com',
    storageBucket: 'e-commrce-4c2bb.firebasestorage.app',
    measurementId: 'G-SR99X4N103',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0heZHjTAoJmaQ5zqqEjZZCtTf32-MrQc',
    appId: '1:193187845880:android:80749104620bcb79db0d0d',
    messagingSenderId: '193187845880',
    projectId: 'e-commrce-4c2bb',
    storageBucket: 'e-commrce-4c2bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmVRs2fboel2Icz1lxf5xdVDae8fCbFhk',
    appId: '1:193187845880:ios:06550e7b2553490adb0d0d',
    messagingSenderId: '193187845880',
    projectId: 'e-commrce-4c2bb',
    storageBucket: 'e-commrce-4c2bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZmL4sM7MAkhNP7eVWZ8r4L2-nDYQUnzw',
    appId: '1:193187845880:web:c9ca58d25dce0384db0d0d',
    messagingSenderId: '193187845880',
    projectId: 'e-commrce-4c2bb',
    authDomain: 'e-commrce-4c2bb.firebaseapp.com',
    storageBucket: 'e-commrce-4c2bb.firebasestorage.app',
    measurementId: 'G-CX4BQMY3PT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmVRs2fboel2Icz1lxf5xdVDae8fCbFhk',
    appId: '1:193187845880:ios:06550e7b2553490adb0d0d',
    messagingSenderId: '193187845880',
    projectId: 'e-commrce-4c2bb',
    storageBucket: 'e-commrce-4c2bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

}